### ISSUE TITLE
My char just stands still while non-FATE mob kill me.

### ISSUE THREAD

**Issue by Fung-Alexander** [pot0to/pot0to-SND-Scripts#1]
Hey, thanks for this script. I've been using it a lot in Heritage Found.

I've run into a consistent problem where if my character aggros a random mob, then he just stands there taking auto-attacks until until death. He then respawns, teleports back to the area and continues FATE farming. The specific conditions seem to be as follows:

- Character finishes a FATE
- Script searches for the next FATE
- Character starts to either mount or teleport
- Random monster aggros and interrupts the traveling
- Character stands there until death

This happens frequently enough that I felt compelled to ask for a solution.

**Comment by pot0to** [comment]
Does your character target the mob when it aggros you? If not, will it at least engage in combat if you manually target it?

**Comment by Fung-Alexander** [comment]
It does not. I've tried various RSR setting like auto switching to manual when attacking, hard targetting, turning on/off FATE prio etc. Nothing work except me manually clicking the mob so it gets attacked for a split second but it immediately gets untargetted again.

**Comment by pot0to** [comment]
Next time this happens can you type /xllog in your chat, right click the copy button to copy all, and send everything to me? https://discord.gg/punishxiv > ffxiv-snd (channel) > pot0to's fate script (thread)
