### ISSUE TITLE
Materia extraction error with Fishing Orange Scrips script

### ISSUE THREAD

**Issue by moffinz** [pot0to/pot0to-SND-Scripts#12]
Not sure if it's something weird on my end, but when I start the script with gear ready for materia extraction I get the error message "[SND] Failure while running (step 8): Addon Materialize not ready."

adding "yield("/wait 0.1")" under the "yield("/generalaction \"Materia Extraction\"")" line seems to fix it, so I dunno if the script checks for the menu too quickly maybe?

**Comment by pot0to** [comment]
Ah you're exactly right. The script is spamming the command to open the materia extraction window and not giving it time to open properly before checking and spamming again. Seems like other people are also running into this problem, so I've updated it to add a 1s wait time to accommodate slower machines. Thanks for the debugging!
