### ISSUE TITLE
Umbral diadem getting stuck at first tree. 

### ISSUE THREAD

**Issue by Dazzurr** [pot0to/pot0to-SND-Scripts#21]
As per title.

When running the diadem OR umbral diadem script, it will occasionally get stuck in the first tree from the initial starting position after phasing into the diadem.

This doesn't always happen, some times it will path slightly around the tree whilst others it attempts to go straight through it rendering it unable to get to the next navigation point.

**Comment by pot0to** [comment]
[10451881ad4cbf363dd200260dd4dd8e5d1cf725](url)
