### ISSUE TITLE
Firmament gathering slot not work

### ISSUE THREAD

**Issue by zackfair1991** [pot0to/pot0to-SND-Scripts#3]
Hello. The gathering slot 1>8 doesn't work at all.
It only gathers the 4th slot.

**Comment by pot0to** [comment]
Should be fixed in efecbb593c40185b76c698f6974b106d20c61108 now, please give it a try and close this ticket if it works.

**Comment by Kalen666666** [comment]
I didn't move whatever the route I choose.
I can move to Summoning Bell  on entrance NPC, but I didn't target or click it.

**Comment by pot0to** [comment]
Hi Kalen,

I got the email about this but I can't see the original comment. If you
still need help with this, please open up a new issue ticket and I'll help
you through there. In the meantime, you can type /xllog in your chatbox to
open up the log window and filter for SND to see where it's getting stuck.

--
Thanks,
pot0to
