### ISSUE TITLE
Can you write one“Once you have obtained twelve unique varieties of atma, you may present them to Jalzahn to have a relic weapon zenith enhanced.“

### ISSUE THREAD

**Issue by tianzhongkun** [pot0to/pot0to-SND-Scripts#4]
一共十二个魂晶 对应的ID和地图在这里 地图后面的这个id是当前地图的ID
白羊之魂晶	7856 	盛夏农庄			134
双鱼之魂晶	7859	莫拉比造船厂		135
巨蟹之魂晶	7862	小麦酒港			138
宝瓶之魂晶	7853	石绿湖营地		139
狮子之魂晶	7858	瞭望阵营地		180
室女之魂晶	7851	弯枝牧场			148
摩羯之魂晶	7854	霍桑山寨			152
人马之魂晶	7860	秋瓜浮村			154
双子之魂晶	7857	地平关			140
天秤之魂晶	7861	黑尘驿站			141
金牛之魂晶	7855	枯骨营地			145
天蝎之魂晶	7852	小阿拉米格		146

**Comment by pot0to** [comment]
Please try the new script: https://github.com/pot0to/pot0to-SND-Scripts/blob/main/Fate%20Farming/Atma%20Farming.lua
Instructions for setup are in the README

**Comment by tianzhongkun** [comment]
Thank you
