### ISSUE TITLE
Instructions ?

### ISSUE THREAD

**Issue by sigmaphi007** [pot0to/pot0to-SND-Scripts#5]
How to use, please ?

**Comment by pot0to** [comment]
Which one are you trying to use? And how did you find the repo?

**Comment by sigmaphi007** [comment]
Someome posted in on a discord from Combat-reborn so I thought it can be used with dalamud

**Comment by pot0to** [comment]
This repo contains a lot of random scripts for stuff I don't want to manually do -- lots of crafting/gathering stuff, some jump puzzle stuff, fate farm stuff, etc. Which one in particular were you looking for?

Also check out the SND repo and the Punish discord: that's where you'll want to start with all of this.
https://github.com/[Jaksuhn/SomethingNeedDoing](https://github.com/Jaksuhn/SomethingNeedDoing)
https://discord.com/channels/1001823907193552978/1196163718216679514

**Comment by sigmaphi007** [comment]
Thank you, I'm interested in the FATE one please

**Comment by pot0to** [comment]
Download the SND plugin first, then checkout these instructions: https://github.com/pot0to/pot0to-SND-Scripts/tree/main/Fate%20Farming

**Comment by sigmaphi007** [comment]
Thank you very much, it is working as intended :)
