### ISSUE TITLE
Firmanent auto abandon

### ISSUE THREAD

**Issue by zackfair1991** [pot0to/pot0to-SND-Scripts#7]
Sorry I didnt have time to check after you fix last issue about gather slot.
After that fix, now, right after entering Diadem, it auto out and become in out loop.

**Comment by pot0to** [comment]
Can you type /xllog in chat, right click the copy button, and send me everything?

**Comment by pot0to** [comment]
Try updating to version 0.1.3
There was a typo with the name of the guy who sold fishing bait, and since the script couldn't find him, it kept trying to restart the loop

**Comment by zackfair1991** [comment]
thank you it works now
