### ISSUE TITLE
I think there is a problem with repair

### ISSUE THREAD

**Issue by zackfair1991** [pot0to/pot0to-SND-Scripts#8]
[SND] Failure while running script: [string "chunk"]:863: attempt to index a nil value (global 'SelectedZone')
![image](https://github.com/user-attachments/assets/7a230185-f725-442b-898f-450c3748ef44)

Although I am putting selfrepair = true but it seems not work

**Comment by pot0to** [comment]
Try v0.1.4
I copy/pasted the repair stuff from the fate script and forgot to change some settings

**Comment by zackfair1991** [comment]
thank you. it will take quite a long time to have it start repairing so I just close this.

**Comment by zackfair1991** [comment]
by the way, bait issue:
![image](https://github.com/user-attachments/assets/eb62c79d-583c-4f0e-8181-ce9ee58b4e6d)
![image](https://github.com/user-attachments/assets/7e13dec8-08ee-4ae5-ad60-aca8e1e41cc6)

Besides, can you add an option to ignore fishing, only fish phase 2 & 3?

**Comment by pot0to** [comment]
`"Something Need Doing (Expanded Edition)" is accessing "ObjectTable" outside the main thread. This is deprecated.` is not script related and also isn't an error. This is something the SND plugin dev needs to fix but won't affect any scripts you run.

`/bait` should be fixed now

What does phase 2 & 3 mean? (I don't actually know much about how the Diadem works, I just cobbled together this script using bits and pieces of other people's stuff and 10min of googling fishing holes lmao)
