### ISSUE TITLE
Fate Farming issue

### ISSUE THREAD

**Issue by VictoriqueReimu** [pot0to/pot0to-SND-Scripts#9]
[SND] Failure while running script: [string "chunk"]:142: global 'HasPlugin' is not callable (a nil value)

**Comment by pot0to** [comment]
Can you check the top of your script for what version you're using? Newest is 2.18.5

**Comment by VictoriqueReimu** [comment]
I updated to the newest verision. And then it shows that [SND] Failure while running script: [string "chunk"]:63: global 'GetItemCount' is not callable (a nil value)

**Comment by pot0to** [comment]
type /xllog in chat, right click the copy button to copy all, and send it to me

**Comment by VictoriqueReimu** [comment]
Log doesn't show anything about snd.

**Comment by pot0to** [comment]
Please send it to me anyways. Without that log, I cannot help you
